image: gitpod/workspace-dotnet:latest
tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
vscode:
  extensions:
    - muhammad-sammy.csharp

